### ISSUE TITLE
A shortcut function for pinging

### ISSUE THREAD

**Issue by cuu508** [pauldenver/healthchecks-io-client#1]
It would be nice if there was a shorthand version for the common case of signalling success. Currently I can do:

```
const { HealthChecksPingClient } = require('healthchecks-io-client');

const pingClient = new HealthChecksPingClient({
  uuid: 'my-uuuid-here',
});

pingClient.success();
```

How about adding a wrapper function that would let me do something like:

```
const { ping } = require('healthchecks-io-client');
ping("my-uuid-here");

```

**Comment by pauldenver** [comment]
That is a great idea. I just included this functionality in the newest version (v1.0.3). Thanks!
