### ISSUE TITLE
"Error: timeout of 5000ms exceeded"

### ISSUE THREAD

**Issue by avasilic** [pauldenver/healthchecks-io-client#2]
Hey there,

I'm getting the error `timeout of 5000ms exceeded` almost daily. Sentry seems to trace the issue to `<PingClient>.start()`. The full error getting outputted is:

```js
{
	error: {
		code: 503,
		error: upstream connect error or disconnect / reset before headers.reset reason: remote refused stream reset,
		headers: [Object],
		rateLimit: [undefined],
		type: response
	}
}
```

**Comment by pauldenver** [comment]
@net-tech have you tried increasing the `timeout` option for the ping client?

**Comment by avasilic** [comment]
@pauldenver I haven't. I'll try 10 000ms and reopen this if it does not work.
